### ISSUE TITLE
Keeping the .env

### ISSUE THREAD

**Issue by nicka** [silvermine/serverless-plugin-write-env-vars#2]
First of all wonderful plugin. However I do have some issues with the ux. Let's say your adding new ENV variables and you want to verify the .env is correct.

```
Serverless: Wrote .env file to /Users/nickdenengelsman/Development/serverless/foo/.env
Serverless: Packaging service...
Serverless: Deleted .env file from /Users/nickdenengelsman/Development/serverless/foo/.env
Serverless: Did not deploy due to —noDeploy
```

When you add new vars the only way to verify the .env file is to check the zip for it’s contents. Would it be possible to keep the `.env` file within the project?

**Comment by johncmckim** [comment]
I would suggest going the cleanup step on `deploy: cleanup` which is executed at the start of the deploy lifecycle. This leaves the `.env` file in `.serverless` after the deploy.

**Comment by nicka** [comment]
@johncmckim Sounds good to me!

**Comment by annatrivino** [comment]
@johncmckim I am a newbie to Serverless Framework.  Can you elaborate further how I can used deploy:cleanup?

**Comment by jthomerson** [comment]
@nicka can you use the built-in `sls deploy -n` functionality? (or `--noDeploy`)?

**Comment by jthomerson** [comment]
Re-open if that does not satisfy your needs for some reason.
