### ISSUE TITLE
External .env

### ISSUE THREAD

**Issue by marcelocbf** [silvermine/serverless-plugin-write-env-vars#4]
Hi, I was wondering what would be the recommended approach when you already have a .env file with sensitive info that you don't want to put into serverless.yml. I was moving my project to use sls v1 and needed to put some sensitive info into .env to be loaded by dotenv, but using the plugin, the .env file I create manually is overwritten.

Thanks

**Comment by michalsanger** [comment]
Just a hack until Serverless will support ENV vars. In `package.json`:

```
"scripts": {
  "deploy": "mv .env .env.backup; sls deploy; mv .env.backup .env"
}
```

And deploy with `npm run deploy`

**Comment by marcelocbf** [comment]
Hey @michalsanger Thanks for the answer ... I'm just confused how will my "secret" .env get merged with the one created by the plugin? That's what I needed to accomplish. From what I could understand it would only save it from being overwritten, right? Getting your idea, I thought about using cat to append its contents after sls deploy but by then, the zip has been already created and uploaded, I believe...

**Comment by michalsanger** [comment]
@marcelocbf I came up with this solution in `serverless.yml`, rewrite `.env` into YAML syntax and load vars like this:

```
custom:
  writeEnvVars:
    ACCESS_TOKEN: ${file(./.env.yml):ACCESS_TOKEN}
```

**Comment by marcelocbf** [comment]
Genius! :-) Thanks!
